[package]
name = "led"
version = "0.1.0"
edition = "2021"

[dependencies]
async-channel = "2.3.1"
esp-idf-svc = { version = "0.51.0", default-features = false, features = [
    "std",
] }
rgb = "0.8.50"
